language: ruby
cache: bundler
env:
  - JEKYLL_ENV=prod
install:
  - bundle install
script:
  - bundle exec jekyll build
deploy:
  - provider: script
    script: curl -i -X POST ${DEPLOY_BASE_URL}?token=$TOKEN
    skip_cleanup: true
    on:
      branch: master
