title: Hourai Teahouse
email: contact@houraiteahouse.net
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://houraiteahouse.github.io"

# Third Party Integrations
disqus: hourai-teahouse
google-analytics: UA-82900227-4

# Social Media
discord: VuZhs9V
facebook: HouraiTeahouse
twitter: HouraiTeahouse
github: HouraiTeahouse

# Localization Settings
languages: ["en", "es", "fr", "de", "jp"]

# Asset Settings
assets:
  sources:
    - _assets/img
    - _assets/css
    - _assets/sass

# Build settings
markdown: kramdown
plugins:
  - bootstrap
  - jekyll-assets
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
    values:
      layout: base

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
